### ISSUE TITLE
YKQuality video exchanged

### ISSUE THREAD

**Issue by miguelrc86** [YasKuraishi/YKMediaPlayerKit#3]
Hi!

Pretty "nano bug" here ;-)

switch (quality) {
        case YKQualityLow:
            strURL = self.videos[@"medium"];
            break;
        case YKQualityMedium:
            strURL = self.videos[@"small"];
            break;
        case YKQualityHigh:
            strURL = self.videos[@"hd720"];
    }

**Comment by YasKuraishi** [comment]
Done.
