### ISSUE TITLE
unable to run sample in xcode 6.1

### ISSUE THREAD

**Issue by aks0020** [YasKuraishi/YKMediaPlayerKit#5]
getting this linker error (when I run on device ):
/Library/Developer/Xcode/DerivedData/YKMediaPlayerKit-fzhbvsxszvyoyqetzxccwelqfirz/Build/Products/Debug-iphoneos/DemoAppTests.xctest/DemoAppTests normal armv7

file not found: /Users/userfolder/Library/Developer/Xcode/DerivedData/YKMediaPlayerKit-fzhbvsxszvyoyqetzxccwelqfirz/Build/Products/Debug-iphoneos/YKMediaHelper.app/YKMediaHelper
(& when I run in simulator )
/Library/Developer/Xcode/DerivedData/YKMediaPlayerKit-fzhbvsxszvyoyqetzxccwelqfirz/Build/Products/Debug-iphonesimulator/DemoAppTests.xctest/DemoAppTests normal x86_64

**Comment by YasKuraishi** [comment]
Sorry guys, I need to recompile it with the required architectures, will do later on tomorrow.

**Comment by cloudjanak** [comment]
Thank you ..
Waiting for your Upddation

**Comment by YasKuraishi** [comment]
I updated the architectures, please can you take a look?

**Comment by EzimetYusup** [comment]
still getting getting this linker error  file not found: /Users/otkurbiz/Library/Developer/Xcode/DerivedData/YKMediaPlayerKit-cchcbrsacdfuaudtpjumhmbzotuj/Build/Products/Debug-iphonesimulator/YKMediaHelper.app/YKMediaHelper
clang: error: linker command failed with exit code 1 (use -v to see invocation)
